### Homework 3 Numpy Arrays and Pandas

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into a numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [113]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. (2 pts) What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [150]:
df = pd.read_csv('cars.csv',delimiter=';')

car_dtype = df['Car'].dtype
mpg_dtype = df['MPG'].dtype
horsepower_dtype = df['Horsepower'].dtype
origin_dtype = df['Origin'].dtype

print("Car's data type is:",car_dtype)
print("MPG's data type is:",mpg_dtype)
print("Horsepower's data type is:",horsepower_dtype)
print("Origin's data type is:",origin_dtype)

Car's data type is: object
MPG's data type is: float64
Horsepower's data type is: float64
Origin's data type is: object


2. (1 pt) `numpy` is often imported as `np`. What is this action called? Why might you do this? 

#### Aliasing, we might do this to make it easier to call it as it is shorter.

3. (2 pts) Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [161]:
print("MPG has",mpg.ndim,"dimension(s)")
print("Car has",car.ndim,"dimension(s)")
print("Cylinders has",cylinders.ndim,"dimension(s)")
print("Displacement has",displacement.ndim,"dimension(s)")
print("Horsepower has",horsepower.ndim,"dimension(s)")
print("Weight has",weight.ndim,"dimension(s)")
print("Acceleration has",acceleration.ndim,"dimension(s)")
print("Model has",model.ndim,"dimension(s)")
print("Origin has",origin.ndim,"dimension(s)")


MPG has 1 dimension(s)
Car has 1 dimension(s)
Cylinders has 1 dimension(s)
Displacement has 1 dimension(s)
Horsepower has 1 dimension(s)
Weight has 1 dimension(s)
Acceleration has 1 dimension(s)
Model has 1 dimension(s)
Origin has 1 dimension(s)


4. (3 pts) What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help) (1 pt extra credit)

In [160]:
import pandas as pd
import numpy as np

df = pd.read_csv('cars.csv',delimiter=';')

print(df['Horsepower'].sum()) 
print(df['Horsepower'].min())
print(df['Horsepower'].median())
print(df['Horsepower'].max())
print(df['Horsepower'].mode())


42033.0
0.0
93.5
230.0
0    150.0
Name: Horsepower, dtype: float64


5. (2 pts) Select the last element in each subarray (do this with one operation.)

In [129]:
select_more = np.array([[1,2,3],
                        [4,5,6], 
                        [7,8,9]])
# returns array([3, 6, 9])


In [159]:
select_more[:,2]

array([3, 6, 9])

6. (2 pts) Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [158]:
import pandas as pd
import numpy as np

df = pd.read_csv('cars.csv')

np.lookfor('log')

np.log(mpg)

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

C:\Users\aga20\AppData\Local\Temp\ipykernel_7364\2549568028.py:8: RuntimeWarning: divide by zero encountered in log
  np.log(mpg)


array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

7. (2 pts) Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [157]:
# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

origin_array = df['Origin']

US_array = origin_array == 'US'


US_array.values

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

8. (2 pts) Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [156]:
import pandas as pd
import numpy as np

df = pd.read_csv('cars.csv',delimiter=';')

origin_array = df['Origin']

US_array = origin_array == 'US'


df[US_array]

Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
400           Chevrolet Camaro  27.0          4         151.0        90.0   
401            Ford Mustang GL  27.0          4         140.0        86.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model Origin  
0    3504.0          12.0     70     US  
1    3693.0          11.5     70     US  
2    3436.0          11.0     70     US  
3    3433.0          12.0     70     US  
4    3449.0          10.5     70     US  
..      ...           ...    ...    ...  
400  2950.0          17.3     82     US  
401  2790.0          15.6     82     US  
403  2295.0          11.6     82     US  
404  2625.0          18.6     82     US  
405  2720.0          19.4     82     US  

[254 rows x 9 columns]

### Use numpy or pandas to answer the following questions.

9. (3 pts) What is the average horsepower for `Europe` cars? (Hint: create a boolean index of 'US' apply it to horsepower and perform the calculation.)

In [155]:
import pandas as pd
import numpy as np

df = pd.read_csv('cars.csv', delimiter=';')

origin_array2 = df['Origin'] == 'Europe'

print("The average horspower for Europe cars is",df[origin_array2]['Horsepower'].mean())


The average horspower for Europe cars is 78.78082191780823


10. (3 pts) On average are Japanese cars more fuel-efficient than US cars? Show the code that you used to determine this.  

In [152]:
import pandas as pd
import numpy as np
import math
import statistics

df = pd.read_csv('cars.csv', delimiter=';')



df1 = df.groupby('Origin')

df1[['MPG']].agg({'MPG':'mean'})


# Japanese cars are more fuel efficient than US cars on average.


#print(df.groupby('Origin')['MPG'].mean())

MPG
Origin           
Europe  26.745205
Japan   30.450633
US      19.688189

11. (3 pts) What is the correlation coefficient of `mpg` and `weight`? What is a correlation coefficient? What does the result indicate about the relationship between mpg and weight? 

In [123]:
import pandas as pd
import numpy as np
import math
import statistics

df = pd.read_csv('cars.csv',delimiter=';')

np.corrcoef(df['MPG'],df['Weight'])

# The correlation coefficient is -0.787. A correlation coefficient is a number that describes how strong of a correlation there is between 2 values.
# The results indicate that there is a negative correlation between MPG and weight of ~79%. 



array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])

Extra credit: (3 pts) Create a new pandas dataframe that has the average mpg, weight, and horsepower per country of origin

In [151]:
import pandas as pd
import numpy as np
import math
import statistics

df = pd.read_csv('cars.csv',delimiter=';')



df1 = df.groupby('Origin')

df1[['MPG','Weight','Horsepower']].agg({'MPG':'mean','Weight':'mean','Horsepower':'mean'})




MPG       Weight  Horsepower
Origin                                    
Europe  26.745205  2431.493151   78.780822
Japan   30.450633  2221.227848   79.835443
US      19.688189  3372.700787  118.011811